version: '3.8'
services:
  postgres:
    build: .
    container_name: postgres_ext
    environment:
      - POSTGRES_PASSWORD=qcyz
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    # 必须加上下面的 command，让 Apache AGE 在启动时就加载
    command: 
      - -c
      - shared_preload_libraries=age

volumes:
  pg_data: